# Data Lists

# 100 items
list_integers_unique_sorted = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100]

# 100 items
list_integers_unique_unsorted = [61,48,15,85,70,34,81,45,74,53,27,90,84,98,67,64,14,32,17,57,18,72,19,24,7,97,62,56,10,36,9,55,76,25,8,28,80,6,4,22,40,52,13,12,86,11,43,26,46,49,51,88,44,87,23,66,82,50,31,77,21,100,89,42,30,60,37,20,71,73,2,54,47,3,91,92,83,35,38,94,1,59,96,65,29,16,75,79,41,99,63,5,95,78,33,58,68,93,39,69]

# 200 items
list_alpha_unique_sorted = ['adfnogvt','ajntspld','aotdmwzg','aoumtscv','apeucshw','aphyzdws','aqhvxuko','arhzqtiw','arwxplzj','atfecwrp','avopsndb','awlgpuin','blycqxgi','bmhdnwva','bokdqsev','bordsgqh','btqkusle','bycxtadp','byxkoufp','cudqksrj','cuqyzdvt','cyptkens','czwhgvdq','dabnefrq','daekvuxy','dbahklfv','dbwunspm','dgvfwyne','divoksye','dkobyght','dmjhpeak','dolapxhi','dwljhibm','easwqbov','eayxcfgo','ekiamrxy','enltrbvc','eraupzwk','exavtwio','exkijqul','faectjyx','fbjkaump','fgxedoqt','fhykmwgv','fituyhzr','fjcnqbpv','fpaehigl','fuiqzvre','ganyfxew','gbdcjvpi','gezawmvd','ghvlyzke','giqoelrh','glqeydaf','grvsdopm','gupkijzf','hexvzsjg','hlbuivnm','hoalbekr','hoeambif','hovyedag','htaxfgnc','hvjxlidp','iapnlvrk','ijbuwmcd','ijqoalnf','irxoqtmg','itnboklc','iutoqkmf','ivgmfarb','ixfeolcd','ixvgojzl','jbgowupe','jbgyepta','jcwukixv','jenmrbya','jgbvwndx','jklgxyda','jyvspalg','jzcaistg','kmbaqvht','knadgzip','knipbhqd','kodibrqx','kotnmuli','kranpqcd','ktgabcvi','kuhajrcd','lhuegnfp','lqcgwtoj','lrfyjvds','lsytawpo','lvuicrpa','lzapvcjx','macduxql','mdkfclzr','mesrnpak','mjupavdf','mtyoqxaf','mznejygc','mzxcivaq','ncyduotv','neztrajs','nkevqrza','nokymauw','npycfexk','nqgtplic','nyxzqtdm','nzjdmosg','odmfvasb','ofujldtc','ofxtmhsg','ojektydr','onbliexg','orazsejw','ormbkswj','otmyarsu','pavehnsk','pgizmouq','pirzgnqv','pksrnjld','plicabtw','pnxgsfqj','prvoaqhk','psgedlay','ptqcfjyr','pvkacsit','pvzehoua','pwrusbyd','pyrlqixc','qftzrowk','qimoheav','qnweuodf','qwabjgoe','rcqvdhbi','rctybfdk','rizybfpm','rkdotbnh','rtljeokd','rucyqpbl','ruztfqyd','rwoamigb','rwpjxkih','senwlgqx','siahmquo','siluaxjc','spagzbxy','srodpfna','srxqlfch','sxfcarbz','tfbeyzuq','thvaybrl','tkmnyhdp','tpwfbxru','tufpcszo','tyfjxzdu','uafidobr','ubyhlqfa','ujnxwtay','upfkvtza','urmfwjae','uvxiqfdk','uxbtijfn','vbuydgmi','vfospzex','vhsrewya','vimlbjda','vlzwysdh','vmbcjtar','wahqzgxl','wcpyaoud','wdjlbcao','wosfhcge','wvpxfihl','xbgqenla','xbpdokhr','xfsredna','xmtkfszn','xoqgcunz','xzuprnlm','xzvoqtkl','ycdgqabv','ygnomblu','ygzkavmt','ykcpxbia','ylaqwost','ylbtzqdm','ypqdijme','yrqcnbud','yrwjixpt','ysxrovab','zarkhiuo','zbygxdsr','zesatgpr','zetdqymg','ziqjghal','zlpsdgcb','zsvqejgt','ztaklxvi','zvubkrhd']

# 200 items
list_alpha_unique_unsorted = ['qwrbojnz','cefvxriz','toznksrb','xbchrvau','yglzspbm','hgeotajp','jdqwauih','oyrvfcaw','tsydpwcj','nielwjxv','qfzjphxr','axobvrcq','vhqepxjl','okmjtirs','shlbieaf','yvdaftcj','emswjify','weilstdy','xvhzyuet','vbyuoawn','xautvgck','ofheyivn','wkxfmauq','eydcfabt','mwsfihnr','ufcvdbkw','vhpiajes','wpgesait','utczkmaq','iygcmtxz','pfinjsbl','wxudctqj','mejpfqbh','fyzuoksj','hpbomaix','ohegiwzv','uispyxho','wqjceamf','pafdqcsr','dupywxal','yxpvzosl','zxnrqsdb','vxjawicg','budoqkxn','yhpbkcqt','vuhdlkcg','npuegdma','hyxbplra','wazkmurh','wkzincmj','cbfpytea','dgwmoauh','bdhlcwer','knagevdu','fcqemvzi','cfuxzvgl','wamyokbg','ieasrvbu','gibvkwro','einsagzq','kvczfdlo','kchvgyrm','qvpxdren','rtqixvng','krwbejiu','lhdubpjw','alpekrjm','clsfzwjo','oaxdsnug','vuxsgjyk','fglotrnb','crlhjegq','sdgijebx','gpmlvzkd','xfiqmtlv','yeozmckv','zvhwcsed','tardwemv','rjmypszk','naxzgydl','rwgelzfa','phczfuna','cjomqewn','hgvdwmpi','hrznjipo','ipzdkwjt','tafodxnu','aobtmhzg','rpkazdej','gxlbeaqv','flromzdc','aexhrkst','ehradpil','htoqcrad','imocdveq','fycoanje','pgflcqbw','dvguoanh','tnaurqfo','mqtfnjeh','rvladqbh','gxocbdit','gqsrbenh','torswfqc','ulnkvjqc','txaipogl','sxygebac','gujqhbid','riqdjvfs','eitmjrlu','aidfpljz','tfrelwoa','bjqacpiu','lqgrvmei','dlaoxuhv','quztabvl','ahtxmywb','dfpsiawh','cfbaxlew','eqcdajlw','npvmstwq','rampcdtf','cgpawlbt','bzmiqavd','jlehpafz','rnjuabiv','adeqxynw','wqouzfha','lkervucs','ayrvszhk','enksqdha','sjopnwdr','ebmarnlu','gmaofncr','ahdkjlwt','zsbemxky','rcsxphaj','vhbkiutq','hokjifas','hawlscdu','aybjxzdi','npizrhog','abwsdyvm','mpbvkcfj','ywbsmedz','ojmexutf','ltmyqkab','chqagsdz','tjbnhrsz','sjgapckd','hpjtsinx','bpzntalu','nezifsqy','uspzfbaq','jeapwybt','oknhewam','gepzyctn','apxymvik','ewygjslr','aesronqz','uymolqkj','aphbeqki','arlgizty','dkbaiefl','nelqkjrt','wpeqvkgf','ezomcsbp','oijqcdxr','bzeopqdk','jvoytwge','kqalycnx','grajkwvm','ixzhwpod','hcrpoqxd','axrpfbmn','bzxfhosa','koaeqrpf','gokwzrlb','gusyadpj','mgnhvbxy','ozlfsehb','xitrjgzq','ioydlbgm','iwcydmja','lfqgpmva','emajgzch','fqaywmok','mtjdlkca','fbxagovu','hvjnsmez','uzwejoip','xpjdytoq','pbgmhenl','ayncbhdo','sjudwzgl','rojbqedy','zltagyhu','uwpgbhoa','mwhdxnug','joceanuz']

